commerce_payment.commerce_payment_gateway.plugin.payfast:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    merchant_key:
      type: string
      label: 'Merchant Key'
    passphrase:
      type: string
      label: 'Passphrase'
